import {AutoGeneratedId, Entity, MultiTenancyType, Text} from '@kinotic/structures-api'

@Entity(MultiTenancyType.SHARED, true)
export class Email {
    @AutoGeneratedId
    public id!: string
    @Text
    public body!: string

    public to!: string

    public from!: string

    constructor(body: string) {
        this.body = body
    }

}
