import {AutoGeneratedId, Entity, MultiTenancyType, Precision, PrecisionType, Discriminator, NotIndexed, EntityServiceDecorators, Policy, $Policy, $Role} from '@kinotic/structures-api'
import {Address} from './Address.js'
import {Pet} from './Pet.js'

@EntityServiceDecorators(
    {
        allCreate: [
            $Policy([['data:create']]),
            $Role(['admin'])
        ],
    }
)
@Entity(MultiTenancyType.SHARED)
@Policy([['data:read']])
export class Person {
    @AutoGeneratedId
    public id: string | null = null
    public firstName: string = ''

    public lastName: string = ''

    @Precision(PrecisionType.SHORT)
    public age?: number

    public address!: Address

    @Discriminator('type')
    public myPet?: Pet

    @NotIndexed
    public favoriteSaying!: string

}
