import {AutoGeneratedId, Entity, MultiTenancyType, Precision, PrecisionType, Discriminator} from '@kinotic/structures-api'
import {Address} from './Address.js'
import {Pet} from './Pet.js'

@Entity(MultiTenancyType.SHARED)
export class Person {
    @AutoGeneratedId
    public id: string | null = null
    public firstName: string = ''

    public lastName: string = ''

    @Precision(PrecisionType.SHORT)
    public age?: number

    public address!: Address

    @Discriminator('type')
    myPet?: Pet

}
