import { AutoGeneratedId, Entity, MultiTenancyType, NotIndexed } from "@kinotic/structures-api"

@Entity(MultiTenancyType.SHARED)
export class Dashboard {
    @AutoGeneratedId
    public id: string | null = null
    public name!: string
    public description: string | null = null
    public applicationId!: string
    @NotIndexed
    public layout!: string
    public created!: Date
    public updated!: Date
}