import { AutoGeneratedId, Entity, MultiTenancyType, NotIndexed } from "@kinotic/structures-api"

@Entity(MultiTenancyType.SHARED)
export class DataInsightsWidget {
    @AutoGeneratedId
    public id: string | null = null
    public applicationId!: string
    public name!: string
    public description!: string
    @NotIndexed
    public src!: string
    public created!: Date
    public updated!: Date
}