import { AutoGeneratedId, Entity, MultiTenancyType } from "@kinotic/structures-api"

@Entity(MultiTenancyType.SHARED)
export class DataInsightsWidget {
    @AutoGeneratedId
    public id: string | null = null
    public name!: string
    public description!: string
    public created!: Date
    public updated!: Date
}