import { AutoGeneratedId, Entity, MultiTenancyType, NotIndexed } from "@kinotic/structures-api"

@Entity(MultiTenancyType.SHARED)
export class DataInsightsWidget {
    @AutoGeneratedId
    public id: string | null = null
    public applicationId!: string
    public name!: string
    public description!: string
    @NotIndexed
    public src!: string
    public widgetType!: string // chart, table, metric, etc.
    public config!: string // JSON configuration for the widget
    public dashboardId?: string // Optional reference to dashboard
    public created!: Date
    public updated!: Date
}