package org.kinotic.structures.api.domain.insights;

import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.Instant;

/**
 * Represents an individual web component generated by the data insights system.
 * Each component is a self-contained visualization that can be dropped into any page.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DataInsightsComponent {
    
    /**
     * Unique identifier for this component.
     */
    private String id;
    
    /**
     * Human-readable name for the component.
     */
    private String name;
    
    /**
     * Description of what this component visualizes.
     */
    private String description;
    
    /**
     * When this component was last modified.
     */
    private Instant modifiedAt;
    
    /**
     * The complete HTML source code for the web component.
     * This includes the JavaScript class definition and customElements.define() call.
     */
    private String rawHtml;
    
    /**
     * The application ID this component belongs to.
     */
    private String applicationId;
    
    /**
     * Whether this component supports date range filtering.
     * Components that return true will subscribe to global date range changes.
     */
    private Boolean supportsDateRangeFiltering;
} 