package org.kinotic.structures.api.domain.insights;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.time.Instant;
import java.util.List;

/**
 * Response for data insights containing multiple web components
 * and essential metadata for rendering to end users.
 * 
 * This is designed for "data insights lite" mode where users simply want
 * to see their data visualized without any code or technical details.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InsightResponse {
    
    /**
     * List of web components generated by this analysis.
     */
    private List<DataInsightsComponent> components;
    
    /**
     * When this analysis was created.
     */
    private Instant createdAt;
    
    /**
     * Status of the analysis generation.
     */
    private AnalysisStatus status;
    
    /**
     * User-friendly error message if status is ERROR.
     */
    private String errorMessage;
}