import { IEntitiesService } from '@kinotic/structures-api'
import { BaseProductReviewEntityService } from './generated/BaseProductReviewEntityService.js'

/**
 * Service for interacting with ProductReview entities
 * This class was generated by the structures cli
 */
export class ProductReviewEntityService extends BaseProductReviewEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
