import { IEntitiesService } from '@kinotic/structures-api'
import { BaseProductEntityService } from './generated/BaseProductEntityService.js'

/**
 * Service for interacting with Product entities
 * This class was generated by the structures cli
 */
export class ProductEntityService extends BaseProductEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
