spring:
  main:
    allow-circular-references: true

structures:
  elasticUseSsl: ${ELASTIC_USE_SSL}
  elasticUris: "${ELASTIC_URIS}"
  elasticConnectionTimeout: ${ELASTIC_CONNECTION_TIMEOUT}
  elasticSocketTimeout: ${ELASTIC_SOCKET_TIMEOUT}
  elasticUsername: "${ELASTIC_USERNAME}"
  elasticPassword: "${ELASTIC_PASSWORD}"

logging:
  level:
    org:
      kinotic: INFO
