spring:
  devtools:
    livereload:
      port: 35730

structures:
  elasticUseSsl: false
  elasticUris: "localhost:9200"
  elasticConnectionTimeout: 60s
  elasticSocketTimeout: 60s
  elasticUsername: ""
  elasticPassword: ""

logging:
  level:
    org:
      kinotic: TRACE