import {EntityType} from '@/api/idl/EntityType'
import {EsIndexConfigurationData} from '@/api/idl/EsIndexConfigurationData'
import {MultiTenancyType} from '@/api/idl/MultiTenancyType'
import {PrecisionType} from '@/api/idl/PrecisionType'
import type {EntityServiceDecoratorsConfig} from '@/api/idl/EntityServiceDecoratorsConfig'

// These are TC39 stage-3 decorators with no runtime behavior: they are source-level
// markers the Kinotic CLI reads from the TypeScript AST to build entity definitions.

export function AbacPolicy(_expression: string) {
    return function (_target: any, _propertyKey?: string, _descriptor?: PropertyDescriptor): void {
    }
}

/**
 * Signifies that a property is an auto-generated ID for the entity.
 */
export function AutoGeneratedId(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

/**
 * Signifies that a property is a discriminator for the entity.
 * This is used to determine the type of the entity when deserializing from JSON.
 * @param propertyName the name of the property to use as the discriminator
 */
export function Discriminator(_propertyName: string) {
    return function (_value: undefined, _context: ClassFieldDecoratorContext): void {
    }
}

/**
 * Signifies that a class is a Entity.
 * This is required to define the class as an entity in the Kinotic framework.
 * @param multiTenancyType the type of multi-tenancy to use for this entity
 * @param entityType the type of entity to use for this entity
 */
export function Entity(_multiTenancyType: MultiTenancyType = MultiTenancyType.NONE,
                       _entityType: EntityType = EntityType.TABLE) {
    return function (_value: Function, _context: ClassDecoratorContext<any>): void {
    }
}

/**
 * A class Decorator when applied to an Entity will configure Decorators to be applied to the EntityService
 * @param config the {@link EntityServiceDecoratorsConfig} to use
 */
export function EntityServiceDecorators(_config: EntityServiceDecoratorsConfig) {
    return function (_value: Function, _context: ClassDecoratorContext<any>): void {
    }
}

/**
 * Provides configuration for the Elasticsearch index.
 * This can be used to override the default index settings and mappings used by Kinotic.
 */
export function EsIndexConfiguration(_value: EsIndexConfigurationData) {
    return function (_target: Function, _context: ClassDecoratorContext<any>): void {
    }
}

export function Flattened(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

/**
 * Signifies that a property is the ID of the entity.
 */
export function Id(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

export function Nested(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

/**
 * Signifies that a property is not indexed in Elasticsearch.
 */
export function NotIndexed(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

export function NotNull(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

export function Policy(_policies: string[][]) {
    return function (_value: unknown,
                     _context: ClassDecoratorContext<any> | ClassFieldDecoratorContext | ClassMethodDecoratorContext): void {
    }
}

export function Precision(_precisionType: PrecisionType = PrecisionType.INT) {
    return function (_value: undefined, _context: ClassFieldDecoratorContext): void {
    }
}

export function Query(_statements: string) {
    return function (_value: Function, _context: ClassMethodDecoratorContext): void {
    }
}

export function Role(_roles: string[]) {
    return function (_value: unknown,
                     _context: ClassDecoratorContext<any> | ClassFieldDecoratorContext | ClassMethodDecoratorContext): void {
    }
}

export function Text(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

/**
 * This is used for data streams to signify the field that should be used as the time reference.
 */
export function TimeReference(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

export function Version(_value: undefined, _context: ClassFieldDecoratorContext): void {
}

export function TenantId(_value: undefined, _context: ClassFieldDecoratorContext): void {
}
