services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: structures-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - "9200:9200" # allow local kibana or curl usage
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
    volumes:
      - ~/structures/elastic-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: structures-kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 1G
    ports:
      - "5601:5601"
