version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    stdin_open: true
    tty: true
  structures-server:
    image: kinotic/structures-server:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "127.0.0.1:58503:58503"
      - "127.0.0.1:58504:58504"
      - "127.0.0.1:8989:8989"
    environment:
      SPRING_PROFILES_DEFAULT: docker
      ELASTIC_USE_SSL: false
      ELASTIC_URIS: "elasticsearch:9200"
      ELASTIC_CONNECTION_TIMEOUT: 60s
      ELASTIC_SOCKET_TIMEOUT: 60s
      ELASTIC_USERNAME: ""
      ELASTIC_PASSWORD: ""
    stdin_open: true # docker run -i
    tty: true        # docker run -t
