version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
  structures-server:
    image: kinotic/structures-server:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8989/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    ports:
      - "127.0.0.1:58503:58503"
      - "127.0.0.1:58504:58504"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:80:80"
    environment:
      SPRING_PROFILES_ACTIVE: production
      STRUCTURES_INDEX_PREFIX: struct_
      STRUCTURES_ELASTIC_USE_SSL: false
      STRUCTURES_ELASTICCONNECTIONS_0_HOST: elasticsearch
      STRUCTURES_ELASTICCONNECTIONS_0_PORT: 9200
      STRUCTURES_ELASTIC_CONNECTION_TIMEOUT: 60s
      STRUCTURES_ELASTIC_SOCKET_TIMEOUT: 60s
      STRUCTURES_ELASTIC_USERNAME:
      STRUCTURES_ELASTIC_PASSWORD:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
