kinoticVersion=5.0.0-SNAPSHOT

org.gradle.caching=true
org.gradle.parallel=true

allureVersion=2.35.4
antlrVersion=4.13.2
apacheCommonsCompressVersion=1.28.0
apacheCommonsLangVersion=3.20.0
apacheCommonsTextVersion=1.15.0
aspectJVersion=1.9.25.1
azureCommunicationEmailVersion=1.1.4
azureIdentityVersion=1.18.4
azureKeyvaultSecretsVersion=4.11.1
azureResourcemanagerCdnVersion=2.53.10
azureResourcemanagerDnsVersion=2.53.10
azureResourcemanagerNetworkVersion=2.60.1
azureResourcemanagerStorageVersion=2.57.2
azureStorageBlobVersion=12.35.1
caffeineVersion=3.2.4
chronicleBomVersion=2026.20
commonsIoVersion=2.22.0
elasticClientVersion=9.5.1
graalvmPolyglotVersion=25.2.4
groovyVersion=4.0.32
handlebarsVersion=4.5.4
igniteVersion=2.18.0
jakartaAnnotationVersion=3.0.0
jakartaJsonVersion=2.1.3
jreleaserVersion=1.25.0
jsonwebtokenVersion=0.13.0
kinoticSpawnVersion=5.0.0-beta.1
lombokPluginVersion=9.5.0
otelBomVersion=1.65.0
otelInstrumentationBomVersion=2.30.0
slugifyVersion=4.0.1
springAiVersion=1.1.8
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
testcontainersBomVersion=2.0.5
vertxJackson3CodecVersion=0.1.0
vertxStompLiteVersion=6.0.0
vertxVersion=5.1.6
