import { IEntitiesService } from '@kinotic/structures-api'
import { BaseAnimalDenEntityService } from './generated/BaseAnimalDenEntityService.js'

/**
 * Service for interacting with AnimalDen entities
 * This class was generated by the structures cli
 */
export class AnimalDenEntityService extends BaseAnimalDenEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
