import { type IEntitiesService } from '@kinotic/structures-api'
import { BaseDashboardEntityService } from './generated/BaseDashboardEntityService.js'

/**
 * Service for interacting with Dashboard entities
 * This class was generated by the structures cli
 */
export class DashboardEntityService extends BaseDashboardEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
