import { type IEntitiesService } from '@kinotic/structures-api'
import { BaseDataInsightsWidgetEntityService } from './generated/BaseDataInsightsWidgetEntityService.js'

/**
 * Service for interacting with DataInsightsWidget entities
 * This class was generated by the structures cli
 */
export class DataInsightsWidgetEntityService extends BaseDataInsightsWidgetEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
