import { IEntitiesService } from '@kinotic/structures-api'
import { BaseCustomerEntityService } from './generated/BaseCustomerEntityService.js'

/**
 * Service for interacting with Customer entities
 * This class was generated by the structures cli
 */
export class CustomerEntityService extends BaseCustomerEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
