import { IEntitiesService } from '@kinotic/structures-api'
import { BasePurchaseEntityService } from './generated/BasePurchaseEntityService.js'

/**
 * Service for interacting with Purchase entities
 * This class was generated by the structures cli
 */
export class PurchaseEntityService extends BasePurchaseEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
