apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "structures-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "structures-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "structures-server.name" . }}
    spec:
      containers:
        - name: structures-server
          image: {{ if .Values.image.sha }}"{{ .Values.image.repository }}@{{ .Values.image.sha }}"{{ else }}"{{ .Values.image.repository }}:{{ .Values.image.tag }}"{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.properties.structures.healthCheckPath }}"
              port: {{ .Values.properties.structures.webServerPort }}
            initialDelaySeconds: 10
            failureThreshold: 15
            periodSeconds: 10
            timeoutSeconds: 7
          startupProbe:
            httpGet:
              path: "{{ .Values.properties.structures.healthCheckPath }}"
              port: {{ .Values.properties.structures.webServerPort }}
            initialDelaySeconds: 30
            failureThreshold: 15
            periodSeconds: 10
            timeoutSeconds: 7
          livenessProbe:
            httpGet:
              path: "{{ .Values.properties.structures.healthCheckPath }}"
              port: {{ .Values.properties.structures.webServerPort }}
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 30
            timeoutSeconds: 7
          ports:
            - containerPort: {{ .Values.properties.structures.webServerPort }} # UI PORT
            - containerPort: {{ .Values.properties.structures.graphqlPort }} # GraphQL Port
            - containerPort: {{ .Values.properties.structures.openApiPort }} # OpenAPI Port
            - containerPort: 58503 # Continuum Stomp Port
            - containerPort: 58504 # Continuum REST Port
          envFrom:
            - configMapRef:
                name: {{ include "structures-server.fullname" . }}
          volumeMounts:
            - name: tmp-work
              mountPath: /workspace/ignite/work
      restartPolicy: Always
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
        - name: tmp-work
          emptyDir:
            sizeLimit: 1Gi
