apiVersion: v1
kind: Service
metadata:
  name: {{ include "structures-server.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - name: "ui"
      protocol: TCP
      port:  9090 # UI PORTs
      targetPort: 9090
    - name: "graph-ql"
      protocol: TCP
      port: 4000 # GraphQL Port
      targetPort: 4000
    - name: "open-api"
      protocol: TCP
      port: 8080 # OpenAPI Port
      targetPort: 8080
    - name: "stomp"
      protocol: TCP
      port: 58503 # Continuum Stomp Port
      targetPort: 58503
    - name: "rest"
      protocol: TCP
      port: 58504 # Continuum REST Port
      targetPort: 58504
  selector:
    app: {{ include "structures-server.name" . }}
