apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "structures-server.fullname" . }}
data:
  JAVA_TOOL_OPTIONS: "{{ .Values.env.JAVA_TOOL_OPTIONS }}"
  BPL_JAVA_NMT_ENABLED: "{{ .Values.env.ENABLE_NMT }}"
  BPL_JMX_ENABLED: "{{ .Values.env.ENABLE_JMX }}"
  SPRING_PROFILES_ACTIVE: "production"
  STRUCTURES_CORS_ALLOWED_ORIGIN_PATTERN: "*"
  STRUCTURES_INDEX_PREFIX: "{{ .Values.env.STRUCTURES_INDEX_PREFIX }}"
  STRUCTURES_ELASTICCONNECTIONS_0_SCHEME: "{{ .Values.env.STRUCTURES_ELASTIC_SCHEME }}"
  STRUCTURES_ELASTICCONNECTIONS_0_HOST: "{{ .Values.env.STRUCTURES_ELASTIC_HOST }}"
  STRUCTURES_ELASTICCONNECTIONS_0_PORT: "{{ .Values.env.STRUCTURES_ELASTIC_PORT }}"
  STRUCTURES_ELASTIC_CONNECTION_TIMEOUT: "{{ .Values.env.STRUCTURES_ELASTIC_CONNECTION_TIMEOUT }}"
  STRUCTURES_ELASTIC_SOCKET_TIMEOUT: "{{ .Values.env.STRUCTURES_ELASTIC_SOCKET_TIMEOUT }}"
  STRUCTURES_ELASTIC_USERNAME: "{{ .Values.env.STRUCTURES_ELASTIC_USERNAME }}"
  STRUCTURES_ELASTIC_PASSWORD: "{{ .Values.env.STRUCTURES_ELASTIC_PASSWORD }}"
