import {IterablePage, Pageable} from '@kinotic/continuum-client'
import {IEntitiesService, Query, Policy, type TenantSelection} from '@kinotic/structures-api'
import { BasePersonEntityService } from './generated/BasePersonEntityService.js'

export class CityCount {
    public city!: string
    public count!: number
}

export class LastNameCount {
    public lastName!: string
    public count!: number

}


/**
 * Service for interacting with Person entities
 * This class was generated by the structures cli
 */
export class PersonEntityService extends BasePersonEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

    /**
     * Get a count of all people in a given city
     * @param city The city name to get the count for
     */
    @Query('select count(firstName) as count, address.city as city from "struct_city.person" where address.city = ? group by address.city')
    public async countByCity(city: string): Promise<CityCount[]> {
      /** Autogenerated code, changes will be overwritten. **/
      const parameters = [
        {key: 'city', value: city}
      ]
      return this.namedQuery('countByCity', parameters)
    }

    /**
     * Get a count of all people with a given last name
     * @param lastName The last name to get the count for
     * @param pageable The pageable to use for the query
     */
    @Policy([['person:read'], ['person:write', 'person:update']])
    @Query('select count(firstName) as count, lastName from "struct_city.person" where lastName = ? group by lastName')
    public async countByLastName(lastName: string, pageable: Pageable): Promise<IterablePage<LastNameCount>> {
      /** Autogenerated code, changes will be overwritten. **/
      const parameters = [
        {key: 'lastName', value: lastName}
      ]
      return this.namedQueryPage('countByLastName', parameters, pageable)
    }
}
