/**
 * Represents an individual web component generated by the data insights system.
 * Each component is a self-contained visualization that can be dropped into any page.
 */
export interface DataInsightsComponent {
    
    /**
     * Unique identifier for this component.
     */
    id: string;
    
    /**
     * Human-readable name for the component.
     */
    name: string;
    
    /**
     * Description of what this component visualizes.
     */
    description: string;
    
    /**
     * When this component was last modified.
     */
    modifiedAt: string; // ISO date string
    
    /**
     * The complete HTML source code for the web component.
     * This includes the JavaScript class definition and customElements.define() call.
     */
    rawHtml: string;
    
    /**
     * The application ID this component belongs to.
     */
    applicationId: string;
    
    /**
     * Whether this component supports date range filtering.
     * Components that return true will subscribe to global date range changes.
     */
    supportsDateRangeFiltering?: boolean;
} 