import type { IEntitiesService } from '@kinotic/structures-api'
import { BaseOrderEntityService } from './generated/BaseOrderEntityService.js'

/**
 * Service for interacting with Order entities
 * This class was generated by the structures cli
 */
export class OrderEntityService extends BaseOrderEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
