import { IEntitiesService } from '@kinotic/structures-api'
import { BaseAlertEntityService } from './generated/BaseAlertEntityService.js'

/**
 * Service for interacting with Alert entities
 * This class was generated by the structures cli
 */
export class AlertEntityService extends BaseAlertEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
