import { IEntitiesService } from '@kinotic/structures-api'
import { BaseEmailEntityService } from './generated/BaseEmailEntityService.js'

/**
 * Service for interacting with Email entities
 * This class was generated by the structures cli
 */
export class EmailEntityService extends BaseEmailEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
