import { IEntitiesService } from '@kinotic/structures-api'
import { BasePersonWithTenantEntityService } from './generated/BasePersonWithTenantEntityService.js'

/**
 * Service for interacting with PersonWithTenant entities
 * This class was generated by the structures cli
 */
export class PersonWithTenantEntityService extends BasePersonWithTenantEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
