import { IAdminEntitiesService } from '@kinotic/structures-api'
import { BasePersonWithTenantAdminEntityService } from './generated/BasePersonWithTenantAdminEntityService.js'

/**
 * Admin Service for interacting with PersonWithTenant entities
 * This class was generated by the structures cli
 */
export class PersonWithTenantAdminEntityService extends BasePersonWithTenantAdminEntityService {

  constructor(adminEntitiesService?: IAdminEntitiesService) {
    super(adminEntitiesService)
  }

}
