/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationSidebar: typeof import('./src/components/ApplicationSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    DashboardWidgetCard: typeof import('./src/components/DashboardWidgetCard.vue')['default']
    EntityDefinitionDiagram: typeof import('./src/components/entity-definitions/EntityDefinitionDiagram.vue')['default']
    EntityDefinitionNode: typeof import('./src/components/entity-definitions/flow-components/EntityDefinitionNode.vue')['default']
    EntityDefinitionSettings: typeof import('./src/components/entity-definitions/sidebar-dashboard/EntityDefinitionSettings.vue')['default']
    EntityDefinitionSidebarDashboard: typeof import('./src/components/entity-definitions/EntityDefinitionSidebarDashboard.vue')['default']
    EntityDefinitionsList: typeof import('./src/components/EntityDefinitionsList.vue')['default']
    EntityPagination: typeof import('./src/components/entity-list/EntityPagination.vue')['default']
    EntityTableBody: typeof import('./src/components/entity-list/EntityTableBody.vue')['default']
    EntityTableHeaders: typeof import('./src/components/entity-list/EntityTableHeaders.vue')['default']
    EntityTableToolbar: typeof import('./src/components/entity-list/EntityTableToolbar.vue')['default']
    EnumNode: typeof import('./src/components/nodes/EnumNode.vue')['default']
    ERTable: typeof import('./src/components/modals/ERTable.vue')['default']
    GitHubLinkStatus: typeof import('./src/components/GitHubLinkStatus.vue')['default']
    Glitch: typeof import('./src/components/Glitch.vue')['default']
    GlobalObjectNode: typeof import('./src/components/nodes/GlobalObjectNode.vue')['default']
    InviteEmailTemplateEditor: typeof import('./src/components/InviteEmailTemplateEditor.vue')['default']
    MicroserviceDeploymentsTable: typeof import('./src/components/MicroserviceDeploymentsTable.vue')['default']
    NewProjectSidebar: typeof import('./src/components/NewProjectSidebar.vue')['default']
    ObjectNode: typeof import('./src/components/nodes/ObjectNode.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    PropertyType: typeof import('./src/components/entity-definitions/flow-components/PropertyType.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedWidgetItem: typeof import('./src/components/SavedWidgetItem.vue')['default']
    SetPasswordFields: typeof import('./src/components/SetPasswordFields.vue')['default']
    SocialAuthButton: typeof import('./src/components/SocialAuthButton.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    UiDeploymentsTable: typeof import('./src/components/UiDeploymentsTable.vue')['default']
    UnionNode: typeof import('./src/components/nodes/UnionNode.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
