import { IEntitiesService } from '@kinotic/structures-api'
import { BaseAddressEntityService } from './generated/BaseAddressEntityService.js'

/**
 * Service for interacting with Address entities
 * This class was generated by the structures cli
 */
export class AddressEntityService extends BaseAddressEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
