import { IEntitiesService } from '@kinotic/structures-api'
import { BaseAppointmentEntityService } from './generated/BaseAppointmentEntityService.js'

/**
 * Service for interacting with Appointment entities
 * This class was generated by the structures cli
 */
export class AppointmentEntityService extends BaseAppointmentEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
