import { IEntitiesService } from '@kinotic/structures-api'
import { BaseContactInfoEntityService } from './generated/BaseContactInfoEntityService.js'

/**
 * Service for interacting with ContactInfo entities
 * This class was generated by the structures cli
 */
export class ContactInfoEntityService extends BaseContactInfoEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
