import { IEntitiesService } from '@kinotic/structures-api'
import { BaseDiagnosisEntityService } from './generated/BaseDiagnosisEntityService.js'

/**
 * Service for interacting with Diagnosis entities
 * This class was generated by the structures cli
 */
export class DiagnosisEntityService extends BaseDiagnosisEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
