import { IEntitiesService } from '@kinotic/structures-api'
import { BaseInsuranceInfoEntityService } from './generated/BaseInsuranceInfoEntityService.js'

/**
 * Service for interacting with InsuranceInfo entities
 * This class was generated by the structures cli
 */
export class InsuranceInfoEntityService extends BaseInsuranceInfoEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
