import { IEntitiesService } from '@kinotic/structures-api'
import { BasePatientEntityService } from './generated/BasePatientEntityService.js'

/**
 * Service for interacting with Patient entities
 * This class was generated by the structures cli
 */
export class PatientEntityService extends BasePatientEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
