import { IEntitiesService } from '@kinotic/structures-api'
import { BasePrescriptionEntityService } from './generated/BasePrescriptionEntityService.js'

/**
 * Service for interacting with Prescription entities
 * This class was generated by the structures cli
 */
export class PrescriptionEntityService extends BasePrescriptionEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
