import { IEntitiesService } from '@kinotic/structures-api'
import { BaseProviderEntityService } from './generated/BaseProviderEntityService.js'

/**
 * Service for interacting with Provider entities
 * This class was generated by the structures cli
 */
export class ProviderEntityService extends BaseProviderEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
