import { IEntitiesService } from '@kinotic/structures-api'
import { BaseQualificationEntityService } from './generated/BaseQualificationEntityService.js'

/**
 * Service for interacting with Qualification entities
 * This class was generated by the structures cli
 */
export class QualificationEntityService extends BaseQualificationEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
