import { IEntitiesService } from '@kinotic/structures-api'
import { BaseSpecialtyEntityService } from './generated/BaseSpecialtyEntityService.js'

/**
 * Service for interacting with Specialty entities
 * This class was generated by the structures cli
 */
export class SpecialtyEntityService extends BaseSpecialtyEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
