import { IEntitiesService } from '@kinotic/structures-api'
import { BaseTreatmentEntityService } from './generated/BaseTreatmentEntityService.js'

/**
 * Service for interacting with Treatment entities
 * This class was generated by the structures cli
 */
export class TreatmentEntityService extends BaseTreatmentEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
