/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationSidebar: typeof import('./src/components/ApplicationSidebar.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContainerMedium: typeof import('./src/components/ContainerMedium.vue')['default']
    CrudEntityAddEdit: typeof import('./src/components/CrudEntityAddEdit.vue')['default']
    CrudTable: typeof import('./src/components/CrudTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ERTable: typeof import('./src/components/modals/ERTable.vue')['default']
    Glitch: typeof import('./src/components/Glitch.vue')['default']
    GraphQLModal: typeof import('./src/components/modals/GraphQLModal.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NewProjectSidebar: typeof import('./src/components/NewProjectSidebar.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    ProjectStructuresTable: typeof import('./src/components/ProjectStructuresTable.vue')['default']
    PropertyType: typeof import('./src/components/structures/flow-components/PropertyType.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    Structure: typeof import('./src/components/structures/flow-components/Structure.vue')['default']
    StructureItemModal: typeof import('./src/components/modals/StructureItemModal.vue')['default']
    StructureNode: typeof import('./src/components/structures/flow-components/StructureNode.vue')['default']
    StructureSettings: typeof import('./src/components/structures/sidebar-dashboard/StructureSettings.vue')['default']
    StructureSidebarDashboard: typeof import('./src/components/structures/sidebar-dashboard/StructureSidebarDashboard.vue')['default']
    StructuresList: typeof import('./src/components/StructuresList.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
