export enum AppointmentType {
    NEW_PATIENT = 'NEW_PATIENT',
    FOLLOW_UP = 'FOLLOW_UP',
    CONSULTATION = 'CONSULTATION',
    EMERGENCY = 'EMERGENCY',
    ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
    SPECIALIST_VISIT = 'SPECIALIST_VISIT'
} 