import { Entity, AutoGeneratedId, MultiTenancyType, Text } from '@kinotic/structures-api'
import { PrescriptionStatus } from './PrescriptionStatus'

@Entity(MultiTenancyType.SHARED)
export class Prescription {
    @AutoGeneratedId
    public id: string | null = null

    public medicationName: string = ''

    public dosage: string = ''

    public frequency: string = ''

    public startDate: Date | null = null

    public endDate: Date | null = null

    public refillsRemaining: number = 0

    public totalRefills: number = 0

    public status: PrescriptionStatus = PrescriptionStatus.ACTIVE

    @Text
    public instructions: string = ''

    public pharmacy: string = ''

    public isActive: boolean = true
} 