import { EntityService } from '@kinotic/structures-api'
import { Person } from '../domain/Person'

/**
 * Service for interacting with Person entities
 * This class was generated by the structures cli
 */
export class PersonEntityService extends EntityService<Person>{

    constructor() {
        super('org.kinotic', 'Person')
    }
}
