import {
    AutoGeneratedId,
    Entity,
    EntityType,
    MultiTenancyType,
    NotNull,
    Precision,
    PrecisionType,
    TimeReference
} from '@kinotic/structures-api'

export enum OrderStatus {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED'
}

@Entity(MultiTenancyType.SHARED, EntityType.STREAM)
export class Order {
    @AutoGeneratedId
    public id: string | null = null

    @NotNull
    public orderNumber: string = ''

    public status: OrderStatus = OrderStatus.PENDING

    @NotNull
    public customerId: string = ''

    @Precision(PrecisionType.DOUBLE)
    public totalAmount: number = 0

    @TimeReference
    public orderDate: Date = new Date()
} 