import { 
    Entity, 
    AutoGeneratedId, 
    MultiTenancyType,
    Precision,
    PrecisionType,
    NotIndexed,
    NotNull,
    Text,
    Version
} from '@kinotic/structures-api'
import { Address } from './Address.js'
import { Pet, Dog, Cat } from './Pet.js'

@Entity(MultiTenancyType.SHARED)
export class Person {
    @AutoGeneratedId
    public id: string | null = null

    @NotNull
    public firstName: string = ''

    @NotNull
    public lastName: string = ''

    @Text
    public bio: string = ''

    @Precision(PrecisionType.SHORT)
    public age?: number

    @NotIndexed
    public privateNotes?: string

    public addresses: Address[] = []

    public pet: Dog | Cat | null = null

    @Version
    public version: string | null = null
} 