# General properties shared by all profiles

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com:
      kinotic: INFO

server:
  port: 8989

spring:
  elasticsearch:
    uris: ${STRUCTURES_ELASTIC_URIS:127.0.0.1:9200} # needed for actuator health health checks
