# General properties shared by all profiles

logging:
  level:
    com:
      kinotic: INFO

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  graphql:
    schema:
      printer:
        enabled: true
      file-extensions: [".graphql"]
    graphiql:
      enabled: true
