# General properties shared by all profiles
continuum-gateway:
  dataDir:                  /media/continuum/data/gateway

continuum:
  discovery: zookeeper
  debug: true
  eventBusClusterPort: 57100

