# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: DEBUG

structures:
  initializeWithSampleData: true
#  elastic-username: structures
#  elastic-password: pass79
