# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true

continuum-gateway:
  disableIam: true
  dataDir: /tmp/work

structures:
  openApiSecurityType: BASIC

logging:
  level:
    org:
      springframework:
        web: INFO
      kinotic: TRACE
    io:
      vertx: INFO



