# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true

continuum-gateway:
  disableIam: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      kinotic: TRACE
    io:
      vertx: TRACE

structures:
  elasticUseSsl: false
  elasticUris: "localhost:9200"
  elasticConnectionTimeout: 60s
  elasticSocketTimeout: 60s
  elasticUsername: ""
  elasticPassword: ""
