# General properties shared by all profiles
spring:
  main:
    web-application-type: none

logging:
  level:
    com:
      kinotic: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
