
# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true
  maxNumberOfCoresToUse: 4

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: WARN
      netty:
        util: DEBUG
        buffer: DEBUG

spring:
  ai:
    openai:
      api-key: "-"
      base-url: https://api.x.ai
      chat:
        options:
          model: grok-4

structures:
  initializeWithSampleData: true
  corsAllowedOriginPattern: "https:\\/\\/studio.apollographql.com|http:\\/\\/localhost:\\d+|http:\\/\\/121.0.0.1:\\d+"
  corsAllowedHeaders:
    - "*"
  corsAllowCredentials: true
  elastic-connections:
   - scheme: "http"
     host: "localhost"
     port: "9200"

## Configured for the Keycloak docker-compose setup
## Defaults to Basic Auth using the TemporarySecurityService
# oidc-security-service:
#   enabled: true
#   allowed-issuers:
#     - "http://localhost:8888/auth/realms/master"  
#   authorization-audiences:
#     - "structures-client"

