# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true

continuum-gateway:
  disableIam: true
  dataDir: /tmp/work

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: INFO



