# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: false

continuum-gateway:
  dataDir: /tmp/work

logging:
  level:
    org:
      kinotic: INFO
    io:
      vertx: INFO



