
# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true
  maxNumberOfCoresToUse: 4
#continuum-gateway:
#  stomp:
#    port: 9090

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: DEBUG

structures:
  initializeWithSampleData: true
  corsAllowedOriginPattern: "https:\\/\\/studio.apollographql.com|http:\\/\\/localhost:\\d+|http:\\/\\/121.0.0.1:\\d+"
  corsAllowedHeaders:
    - "*"
  corsAllowCredentials: true

#  openApiPort: 9090
#  graphqlPort: 9090
#  elastic-username: structures
#  elastic-password: pass79
