
# YAML Reference http://www.yaml.org/refcard.html
continuum:
  discovery: sharedfs
  debug: true
  maxNumberOfCoresToUse: 4

logging:
  level:
    org:
      kinotic: TRACE
    io:
      vertx: WARN
      netty:
        util: DEBUG
        buffer: DEBUG

structures:
  initializeWithSampleData: true
  corsAllowedOriginPattern: "https:\\/\\/studio.apollographql.com|http:\\/\\/localhost:\\d+|http:\\/\\/121.0.0.1:\\d+"
  corsAllowedHeaders:
    - "*"
  corsAllowCredentials: true
  elastic-connections:
   - scheme: "http"
     host: "localhost"
     port: "9200"
#  elastic-connections:
#    - scheme: "https"
#      host: "test.com"
#      port: "443"
#    - scheme: "http"
#      host: "host2.com"
#      port: "9200"
#  elastic-password: "test"
#  elastic-username: "bob"
