# General properties shared by all profiles

logging:
  level:
    com:
      kinotic: INFO

server:
  port: 8989

structures:
  elasticUseSsl: ${ELASTIC_USE_SSL}
  elasticUris: "${ELASTIC_URIS}"
  elasticConnectionTimeout: ${ELASTIC_CONNECTION_TIMEOUT}
  elasticSocketTimeout: ${ELASTIC_SOCKET_TIMEOUT}
  elasticUsername: "${ELASTIC_USERNAME}"
  elasticPassword: "${ELASTIC_PASSWORD}"
