services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: structures-elasticsearch-e2e
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#      - _JAVA_OPTIONS=-XX:UseSVE=0
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - "9200:9200" # allow local kibana or curl usage
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
