import "reflect-metadata"
import {MultiTenancyType} from '@/api/idl/decorators/MultiTenancyType'

export enum StructuresDecorator {
    Entity = "__structures-entity__",
    Id = "__structures-id__",
    AutoGeneratedId = "__structures-auto-generated-id__",
    Flattened = "__structures-flattened__",
    Nested = "__structures-nested__",
    Text = "__structures-text__",
    NotNull = "__structures-notnull__",
    Precision = "__structures-precision__",
    Discriminator = "__structures-discriminator__"
}

export class EntityConfig {
    public multiTenancyType: MultiTenancyType

    constructor(multiTenancyType: MultiTenancyType) {
        this.multiTenancyType = multiTenancyType
    }
}

export function Entity(multiTenancyType: MultiTenancyType = MultiTenancyType.NONE) {
    return function (constructor: Function) {
        constructor.prototype._multiTenancyType = multiTenancyType
        Reflect.defineMetadata(StructuresDecorator.Entity, new EntityConfig(multiTenancyType), constructor)
    }
}

export function Id(target: any, propertyKey: string) {
    Reflect.defineMetadata(StructuresDecorator.Id, {}, target, propertyKey)
}

export function AutoGeneratedId(target: any, propertyKey: string) {
    Reflect.defineMetadata(StructuresDecorator.AutoGeneratedId, {}, target, propertyKey)

}

export function Flattened(target: any, propertyKey: string) {
    Reflect.defineMetadata(StructuresDecorator.Flattened, {}, target, propertyKey)
}

export function Nested(target: any, propertyKey: string) {
    Reflect.defineMetadata(StructuresDecorator.Nested, {}, target, propertyKey)
}

export function Text(target: any, propertyKey: string) {
    Reflect.defineMetadata(StructuresDecorator.Text, {}, target, propertyKey)
}

export function NotNull(target: any, propertyKey: string) {
    Reflect.defineMetadata(StructuresDecorator.NotNull, {}, target, propertyKey)
}

export enum PrecisionType {
    /**
     * A double-precision 64-bit IEEE 754 floating point number, restricted to finite values.
     */
    DOUBLE,
    /**
     * A single-precision 32-bit IEEE 754 floating point number, restricted to finite values.
     */
    FLOAT,
    /**
     * A signed 32-bit integer with a minimum value of -231 and a maximum value of 231-1.
     */
    INT,
    /**
     * A signed 64-bit integer with a minimum value of -263 and a maximum value of 263-1.
     */
    LONG,
    /**
     * A signed 16-bit integer with a minimum value of -32,768 and a maximum value of 32,767.
     */
    SHORT
}

export class PrecisionConfig {
    public precisionType: PrecisionType

    constructor(precisionType: PrecisionType) {
        this.precisionType = precisionType
    }
}

export function Precision(precisionType: PrecisionType = PrecisionType.INT){
    return function(target: any, propertyKey: string) {
        Reflect.defineMetadata(StructuresDecorator.Precision, new PrecisionConfig(precisionType), target, propertyKey)
    }
}

export class DiscriminatorConfig {
    public propertyName: string

    constructor(propertyName: string) {
        this.propertyName = propertyName
    }
}

export function Discriminator(propertyName: string){
    return function(target: any, propertyKey: string) {
        Reflect.defineMetadata(StructuresDecorator.Discriminator, new DiscriminatorConfig(propertyName), target, propertyKey)
    }
}
