name: Build and Publish

on:
  push:
    branches:
      - develop
      - main
      - 2.x
    paths-ignore:
      - 'structures-js/**'
      - 'website/**'

jobs:
  gradle_build_and_publish:
    name: Build And Publish Java Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_KEY_PASS

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Publish to Maven Central
#        # We must -Psigning.gnupg.executable=gpg since setup-java provides gpg2 as gpg
#        run: ./gradlew publish -Psigning.gnupg.executable=gpg -Psigning.gnupg.keyName="${{ secrets.GPG_KEY_ID }}" -Psigning.gnupg.passphrase="${{ secrets.GPG_KEY_PASS }}"
#        env:
#          MAVEN_USERNAME: ${{ secrets.MAVEN_TOKEN_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN_PASSWORD }}
#
#      - name: Publish to Docker Hub
#        run: ./gradlew bootBuildImage --publishImage
#        env:
#          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./structures-js/structures-api/compose.yml"

      - name: Run E2E Tests
        run: |
          cd structures-js/structures-api
          ./gradlew pnpmInstall
          ./gradlew pnpmTest
