name: Load Generator Docker Build

on:
  push:
    branches:
      - develop
    paths:
      - 'structures-js/load-generator/**'

jobs:
  build_and_publish:
    name: Build and Publish Load Generator
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./structures-js/load-generator
          push: true
          platforms: linux/amd64,linux/arm64
          tags: kinotic/structures-load-generator:latest
          cache-from: type=registry,ref=kinotic/structures-load-generator:buildcache
          cache-to: type=registry,ref=kinotic/structures-load-generator:buildcache,mode=max

      - name: Add status to Commit
        uses: guibranco/github-status-action-v2@v1.1.13
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Load Generator Docker Build'
          description: 'Docker image built and published successfully'
          state: 'success'
          sha: ${{ github.sha }} 